### ISSUE TITLE
Unable to run the server

### ISSUE THREAD

**Issue by occune** [10se1ucgo/ace.py#2]
After building the server with the MSVC 2022 and running the run.py i get this

```
Traceback (most recent call last):
  File "C:\Users\batya\Downloads\ace.py\run.py", line 6, in <module>
    from aceserver import protocol
  File "C:\Users\batya\Downloads\ace.py\aceserver\protocol.py", line 12, in <module>
    import acemodes
  File "C:\Users\batya\Downloads\ace.py\acemodes\__init__.py", line 5, in <module>
    from aceserver import protocol, connection, types, util
  File "C:\Users\batya\Downloads\ace.py\aceserver\connection.py", line 15, in <module>
    from aceserver import base, protocol, types, weapons, util
  File "C:\Users\batya\Downloads\ace.py\aceserver\types.py", line 274, in <module>
    ENTITIES = {cls.type: cls for cls in Entity.__subclasses__() if cls.type in ENTITY}
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batya\Downloads\ace.py\aceserver\types.py", line 274, in <dictcomp>
    ENTITIES = {cls.type: cls for cls in Entity.__subclasses__() if cls.type in ENTITY}
                                                                    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\batya\AppData\Local\Programs\Python\Python311\Lib\enum.py", line 742, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'NoneType' and 'EnumType'
```

**Comment by 10se1ucgo** [comment]
not sure when that stopped working but i pushed a commit to fix that specific error
